version: 0.0
os: linux
files:
  - source: /
    destination: /vhosts/dev.forkc.org/httpdocs
hooks:
  #  BeforeInstall:
  AfterInstall:
    - location: /scripts/reset-permissions.sh
      timeout: 2
      runas: root
#  ApplicationStart:
#  ApplicationStop:
