version: 0.0
os: linux
files:
  - source: /
    destination: /vhosts/forkc.org/httpdocs
hooks:
  #  BeforeInstall:
  AfterInstall:
    - location: /scripts/reset-permissions.sh
      timeout: 5
      runas: root
#  ApplicationStart:
#  ApplicationStop:
